<h1>Our Training for the TRX-HT</h1>
<br>
Josh Bourden - 200541050
<br>
Iqtier U. Ahammad - 201746187

In [1]:
import cv2
import numpy as np
import os
import mediapipe as mp
import playsound


In [1]:
pip install -i https://pypi.anaconda.org/pypi/simple speech

Looking in indexes: https://pypi.anaconda.org/pypi/simple
ERROR: Could not find a version that satisfies the requirement speech (from versions: none)
ERROR: No matching distribution found for speech
Note: you may need to restart the kernel to use updated packages.


In [6]:
mp_pose = mp.solutions.pose
mp_drawing = mp.solutions.drawing_utils

In [7]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [3]:
def draw_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS ) # Draw pose connections


In [4]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                    mp_drawing.DrawingSpec(color=(145,117,66), thickness=2, circle_radius=2), 
                                    mp_drawing.DrawingSpec(color=(100,66,230), thickness=2, circle_radius=2) ) 


In [ ]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, pose)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        key_pressed= cv2.waitKey(1)&0XFF
        if(key_pressed==ord('q')&0XFF):
            break
    cap.release()
    cv2.destroyAllWindows()

In [23]:
pose = []
for res in results.pose_landmarks.landmark:
    test = np.array([res.x, res.y, res.z, res.visibility])
    pose.append(test)

In [35]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)


In [12]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
  
    return pose

In [24]:
result_test = extract_keypoints(results)

In [25]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 

# Actions that we try to detect
actions = np.array(['bicep_curls', 'chest_press', 'y_row', 'w_row'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30

# Folder start
start_folder = 30

In [ ]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    
    for action in actions:
        # Loop through sequences aka videos

        ## Sounds were used to help give a break between collecting the data. It was physically exhausting to execute this data collection.
        playsound.playsound('alarm.wav')
        playsound.playsound('alarm.wav')
        cv2.waitKey(15000)
        playsound.playsound('alarm.wav')
        playsound.playsound('alarm.wav')
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            playsound.playsound('activation.wav')
            playsound.playsound('activation.wav')
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, pose)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(500)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    
                    cv2.imshow('OpenCV Feed', image)
                
              
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [38]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    
    
    # Loop through sequences aka videos
    playsound.playsound('alarm.wav')
    playsound.playsound('alarm.wav')
    cv2.waitKey(15000)
    playsound.playsound('alarm.wav')
    playsound.playsound('alarm.wav')
    for sequence in range(20,30):
        # Loop through video length aka sequence length
        playsound.playsound('activation.wav')
        playsound.playsound('activation.wav')
        for frame_num in range(sequence_length):

            # Read feed
            ret, frame = cap.read()

            # Make detections
            image, results = mediapipe_detection(frame, pose)

            # Draw landmarks
            draw_styled_landmarks(image, results)
            
            # NEW Apply wait logic
            if frame_num == 0: 
                cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                            cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                # Show to screen
                cv2.imshow('OpenCV Feed', image)
                cv2.waitKey(500)
            else: 
                cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                # Show to screen
                cv2.imshow('OpenCV Feed', image)
            
            # NEW Export keypoints
            keypoints = extract_keypoints(results)
            npy_path = os.path.join(DATA_PATH, "y_row", str(sequence), str(frame_num))
            np.save(npy_path, keypoints)

            # Break gracefully
            if cv2.waitKey(10) & 0xFF == ord('q'):
                break
                    
    cap.release()
    cv2.destroyAllWindows()

In [26]:
for action in actions: 
    
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

In [42]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [43]:
label_map = {label:num for num, label in enumerate(actions)}

In [44]:
label_map

{'bicep_curls': 0, 'chest_press': 1, 'y_row': 2, 'w_row': 3}

In [45]:
sequences, labels = [], []
for action in actions:
    for sequence in np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [48]:
X = np.array(sequences)

In [50]:
y = to_categorical(labels).astype(int)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [4]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [58]:
model = Sequential()
model.add(LSTM(64,return_sequences=True,activation = 'relu', input_shape= (30,132)))
model.add(LSTM(128,return_sequences=True,activation = 'relu'))
model.add(LSTM(64,return_sequences=False,activation = 'relu'))
model.add(Dense(64,activation = 'relu'))
model.add(Dense(32,activation = 'relu'))
model.add(Dense(actions.shape[0],activation = 'softmax'))


In [59]:
model.compile(optimizer='Adam',loss = 'categorical_crossentropy', metrics=['categorical_accuracy'])

In [61]:
model.fit(X_train, y_train, epochs = 2000, callbacks=[tb_callback])

Epoch 1/2000
4/4 [==============================] - 13s 189ms/step - loss: 1.3660 - categorical_accuracy: 0.3333
Epoch 2/2000
4/4 [==============================] - 1s 189ms/step - loss: 1.2355 - categorical_accuracy: 0.2982
Epoch 3/2000
4/4 [==============================] - 1s 169ms/step - loss: 1.1345 - categorical_accuracy: 0.5000
Epoch 4/2000
4/4 [==============================] - 1s 153ms/step - loss: 0.8555 - categorical_accuracy: 0.5000
Epoch 5/2000
4/4 [==============================] - 1s 171ms/step - loss: 0.6329 - categorical_accuracy: 0.6930
Epoch 6/2000
4/4 [==============================] - 1s 198ms/step - loss: 0.5513 - categorical_accuracy: 0.9123
Epoch 7/2000
4/4 [==============================] - 1s 170ms/step - loss: 0.9381 - categorical_accuracy: 0.8421
Epoch 8/2000
4/4 [==============================] - 1s 203ms/step - loss: 2.0817 - categorical_accuracy: 0.9298
Epoch 9/2000
4/4 [==============================] - 1s 202ms/step - loss: 0.6080 - categorical_accuracy

KeyboardInterrupt: 

In [63]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 30, 64)            50432     
                                                                 
 lstm_1 (LSTM)               (None, 30, 128)           98816     
                                                                 
 lstm_2 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 64)                4160      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 4)                 132       
                                                                 
Total params: 205,028
Trainable params: 205,028
Non-trai

In [62]:
res = model.predict(X_test)

In [67]:
actions[np.argmax(res[0])]

'y_row'

In [69]:
actions[np.argmax(y_test[0])]

'y_row'

In [72]:
actions[np.argmax(res[5])]

'bicep_curls'

In [73]:
actions[np.argmax(y_test[5])]

'bicep_curls'

In [79]:
actions[np.argmax(y_test[1])]

'chest_press'

In [77]:
actions[np.argmax(res[1])]

'chest_press'

In [76]:
y_test

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])

In [80]:
model.save('trx.h5')

In [81]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [90]:
yhat = model.predict(X_train)

In [91]:
ytrue = np.argmax(y_train, axis = 1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [93]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[85,  0],
        [ 0, 29]],

       [[85,  0],
        [ 0, 29]],

       [[85,  0],
        [ 0, 29]],

       [[87,  0],
        [ 0, 27]]])

In [106]:
sequence = []
threshold = 0.5



cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, pose)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        keypoints= extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-30:]

        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])

        if res[np.argmax(res)] > threshold:
            pred_pose = actions[np.argmax(res)]
        
        else: 
            pred_pose = "None"
        

        

        cv2.rectangle(image,(0,0),(640,40),(245,117,16),-1)
        cv2.putText(image, str(pred_pose), (3,30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        key_pressed= cv2.waitKey(1)&0XFF
        if(key_pressed==ord('q')&0XFF):
            break
    cap.release()
    cv2.destroyAllWindows()

bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
bicep_curls
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
chest_press
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
w_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
y_row
w_row
w_row
w_row
w_row
bice

KeyboardInterrupt: 

In [96]:
model.predict(np.expand_dims(X_test[0],axis=0))

array([[0.000000e+00, 7.648721e-37, 1.000000e+00, 2.891609e-23]],
      dtype=float32)